import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "500", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <ThemeProvider attribute="class" defaultTheme="dark">
        <Navbar />
        {children}
        <Footer />
      </ThemeProvider>
    </section>
  );
}
